### ISSUE TITLE
HTTP01 conformance test fails

### ISSUE THREAD

**Issue by nak3** [knative-sandbox/net-http01#424]
As per title, 1.8 release hits the issue as https://testgrid.k8s.io/r/knative-own-testgrid/net-http01#release

As per error log, it seems we might hit some Let's encrypt's policy.

```
The ACME server refuses to issue a certificate for this domain name, because it is forbidden by policy
```

**Comment by dprotaso** [comment]
> The ACME server refuses to issue a certificate for this domain name, because it is forbidden by policy

What policy ?

**Comment by dprotaso** [comment]
hmm... from

https://community.letsencrypt.org/t/the-acme-server-refuses-to-issue-a-certificate-for-this-domain-name-because-it-is-forbidden-by-policy/124867


> We block a number of particularly high-profile domains from getting certificates from Let’s Encrypt by default. In order to remove the block, we need all of the following:
> 
> An entity representative must email [security@letsencrypt.org](mailto:security@letsencrypt.org) requesting the change, from an email address with the domain in question.
> 
> The domain owner must have an accredited attorney submit a letter requesting addition or removal from the blocklist. Letter must include: Attorney Name, Firm Name, Firm Phone Number and Email Address, Firm Physical Address, Name of organization being represented, a request that specific domains be added or removed from our blocklist, date of request
> 
> We are only able to entirely remove blocked domains. We cannot whitelist subdomains of a blocked domain.

**Comment by dprotaso** [comment]
Looks like we were always using example.com. My guess is lets encrypt would accept our order and then fail async - now it returns 400 when creating the order.

But the http01 conformance only care DNS names in the spec were accepted by let's encrypt and we set the `status` block - not whether the order is fullfilled.

**Comment by dprotaso** [comment]
Fix upstream - https://github.com/knative/networking/pull/721
