### ISSUE TITLE
Can you give me option cache cert ?

### ISSUE THREAD

**Issue by phamquyhai** [knative-sandbox/net-http01#47]
When staging or sometime, you recreate or deploy service many time. 'net-http01' recall api letsencrypt to get cert. letsencrypt will block you "too many certificates already issued for exact set of domains" 

You can save it in the cache until a certain period of time, or until it expires ....

Thanks

**Comment by mattmoor** [comment]
The secret effectively is the cache today.  We could consider something more in-memory, but it will really only avoid this for a pretty narrow use case.

**Comment by mattmoor** [comment]
Do you want to give this a shot?

**Comment by phamquyhai** [comment]
> Do you want to give this a shot?

Yes, i want
